DEVEX-750 Fix up mParticle standard event names
mparticle-integrations/mparticle-apple-integration-branchmetrics pull request #19
Opened 2018-08-28 18:00 UTC by E-B-Smith

Prefer the event name developer originally used when creating events.

2018-08-28 23:27 UTC, samdozor requested changes
Almost there but still not quite consistent with Android. I think you can remove all of this from the MPEvent processing flow:

```
    addStringField(event.transactionID, Transaction Id);
    addStringField(event.currency, Currency);
    addDecimalField(event.revenue, Total Product Amount);
    addDecimalField(event.shipping, Shipping Amount);
    addDecimalField(event.tax, Tax Amount);
    addStringField(event.coupon, Coupon Code);
    addStringField(event.affiliation, Affiliation);
    addStringField(event.searchQuery, Search);
    [event.customData addEntriesFromDictionary:[self stringDictionaryFromDictionary:mpEvent.customFlags]];
    [event.customData addEntriesFromDictionary:[self stringDictionaryFromDictionary:dictionary]];
    if (mpEvent.category.length) event.customData[@"category"] = mpEvent.category;
```

2018-08-29 00:05 UTC, E-B-Smith commented
Then we don't carry the event information to the BranchEvent.  Android needs to be updated.

2018-08-29 01:04 UTC, samdozor commented
Ah yep - sorry to clarify, I meant just the MPCommerceEvent/Product-related things. 

I've pasted the entire function below annotated with steps:

- Steps 1 & 2: Looks good.
- Steps 3 & 6: I'm not sure what the difference between content items and custom data is, but the code is setting all of the custom attributes of the MPEvent to both. Should we pick one or the other? If it's ok to send the same as both that's fine - that's what Android is doing, too.
- Step 4: this should be removed. This should only happen for MPCommerceEvents as on Android.
- Step 5: This should be removed. Custom flags are meant to be used to triggered particular functionality for a given integration, not just forwarded along.
- Step 7: This seems fine - though it will also be in the info dictionary as `"$Category"` so maybe is duplicative.

```
- (BranchEvent*) branchEventWithStandardEvent:(MPEvent*)mpEvent {

    NSString *eventName = mpEvent.name;
    if (eventName.length == 0) return nil;
    
    //Step 1: create an event with the event's name
    BranchEvent *event = [BranchEvent customEventWithName:eventName];
   
    //Step 2: set the event description to be the same as the name
    event.eventDescription = mpEvent.name;
    NSMutableDictionary *dictionary = [mpEvent.info mutableCopy];
    BranchUniversalObject *object = [self branchUniversalObjectFromDictionary:dictionary];

    //Step 3: Take all of the custom attributes from the MPEvent, and add it to the contentItems"
    if (object) [event.contentItems addObject:object];

    //Step 4: Map various MPCommerceEvent related properties (don't need this)
    addStringField(event.transactionID, Transaction Id);
    addStringField(event.currency, Currency);
    addDecimalField(event.revenue, Total Product Amount);
    addDecimalField(event.shipping, Shipping Amount);
    addDecimalField(event.tax, Tax Amount);
    addStringField(event.coupon, Coupon Code);
    addStringField(event.affiliation, Affiliation);
    addStringField(event.searchQuery, Search);

    //Step 5: Add the custom flags as custom data
    [event.customData addEntriesFromDictionary:[self stringDictionaryFromDictionary:mpEvent.customFlags]];
   
    //Step 6: Add the custom attributes (same dictionary as above) as custom data
    [event.customData addEntriesFromDictionary:[self stringDictionaryFromDictionary:dictionary]];

    //Step 7: Hardcode category
    if (mpEvent.category.length) event.customData[@"category"] = mpEvent.category;

    return event;
}
```

2018-08-29 16:58 UTC, samdozor approved these changes

2018-08-29 16:58 UTC, merged